name: "Terraform Test"

on:
  pull_request:
    branches:
      - '*'


#Special permissions required for OIDC authentication
permissions:
  security-events: write # Needed to upload-sarif
  contents: read # Needed to clone repo
  actions: read # Potentially needed for private repositories (see https://github.com/github/codeql-action/issues/2117)

jobs: 
  check-code:
    runs-on: ubuntu-latest
    defaults:
        run:
          shell: bash
          working-directory: ./
    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@6.0.2

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1

      - name: Terraform Init
        run: terraform init -backend=false

      # Run a terraform fmt to check syntax
      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      # Run a terraform validate
      - name: Terraform Validate
        if: success() || failure()
        run: terraform validate -no-color

      # Run kics scan
      - name: KICS Github Action
        uses: Checkmarx/kics-github-action@v2.1.20
        with:
          path: .
          output_formats: json,sarif
          platform_type: terraform
          output_path: results-dir
          ignore_on_exit: results
          exclude_paths: .terraform
          token: ${{ secrets.IAC_PAT_SECRET }}
          enable_comments: true
          enable_annotations: true
